version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8.11

persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
    root: .
    paths:
      - dist

attach_workspace: &attach_workspace
  attach_workspace:
    at: .

build_artifacts: &build_artifacts
  run:
    name: Installing awscli
    command: |
      cd /tmp
      sudo apt-get install -y python-dev
      curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      unzip awscli-bundle.zip
      sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

restore_cache: &restore_cache
  restore_cache:
    key: dependency-cache-{{ checksum "package.json" }}

save_cache: &save_cache
  save_cache:
    key: dependency-cache-{{ checksum "package.json" }}
    paths:
      - ./node_modules

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
      - run: npm run build
      - *persist_to_workspace

  deploy_dev:
    <<: *defaults
    steps:
      - *attach_workspace
      - *build_artifacts
      - run:
          name: Deploy to a dev environment
          command: aws s3 sync dist s3://${DEV_BUCKET}/${CIRCLE_BRANCH} --delete --acl public-read

  deploy_staging:
    <<: *defaults
    steps:
      - *attach_workspace
      - *build_artifacts
      - run:
          name: Deploy to the staging environment
          command: aws s3 sync dist s3://${STAGING_BUCKET} --delete --acl public-read

  deploy_prod:
    <<: *defaults
    steps:
      - *attach_workspace
      - *build_artifacts
      - run:
          name: Deploy to the prod environment
          command: aws s3 sync dist s3://${PROD_BUCKET} --delete --acl public-read

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - deploy_dev:
          requires:
            - build
          filters:
            branches:
              ignore: master
            tags:
              ignore: /^v.*/

      - deploy_staging:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              ignore: /^v.*/

      - deploy_prod:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
